preprocess-error:
  vocabulary:
    - key: "2001"
      substring: "unexpected symbol:"
      customDesc: "Недопустимый символ в назначении перевода"
      code: "81002"
    - key: "2002"
      substring: "Уточните у получателя"
      code: "81001"
    - key: "3010"
      substring: "Мы заблокировали переводы"
      code: "81003"
    - key: "3011"
      substring: "Система быстрых платежей заблокировала"
      customDesc: "Перевод отклонён Системой быстрых платежей (СБП)"
      code: "81004"
    - key: "3011"
      substring: "Не пройден фрод"
      customDesc: "Перевод отклонён банком получателя"
      code: "81005"
    - key: "3012"
      substring: "отклонен провайдером"
      customDesc: "Перевод отклонён банком получателя"
      code: "81006"
